version: '3.3'

services:
  db:
    container_name: mysql
    image: mysql:5.7
    # restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_example
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_net

  phpmyadmin:
    image: phpmyadmin
    # restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - db_net

  # adminer:
  #   container_name: adminer
  #   image: adminer
  #   ports: 
  #     - "8080:8080"
  #   depends_on: 
  #     - db
  #   networks:
  #     - db_net

volumes:
  db_data:

networks:
  db_net:
